const RU = {
    'days': 'дней',
    'hours': 'часов',
    'minutes': 'минут',
    'seconds': 'секунд',
    'Sort by': 'Сортировать',
    'Time to premiere': 'До премьеры осталось',
    'Star Wars: Rogue Squadron': 'Звёздные войны: Эскадрилья «Изгой»',
    'Episodes:': 'Эпизоды:',
    'Episode (from earliest)':`С первого эпизода`,
    'Episode (from latest)':`С последнего эпизода`,
    'Year (from earliest)': 'От новых к старым',
    'Year (from latest)': 'От старых к новым',
    'Appearance': 'Внешнее описание',
    'Characters': 'Персонажи',
  };